### ISSUE TITLE
Contao Update 4.12.3 -> 4.12.4 - InvalidArgumentException 

### ISSUE THREAD

**Issue by Ainschy** [terminal42/contao-shortlink#12]
`InvalidArgumentException:
Specified non-existing directory "/www/htdocs/xxxxxxxx/CONTAOROOT/vendor/terminal42/contao-shortlink/Entity" as Doctrine mapping source.`

**Comment by aschempp** [comment]
I think this was fixed in 72a067f5eb175057c3b64dad43625a7065648982
