### ISSUE TITLE
Weiterleitungsziel mehr als 255 Zeichen

### ISSUE THREAD

**Issue by FrischBlau** [terminal42/contao-shortlink#17]
Hallo,
beim Weiterleitungziel sind momentan max. 255 Zeichen möglich. Weil es bei den Shortlinks ja darum geht, sehr lange Links einzukürzen, wäre es sinnvoll, mehr Zeichen zuzulassen (z.B. 1000) oder die Begrenzung generell aufzuheben.

**Comment by aschempp** [comment]
changed in 138ffc4ef66e07581621650c7c93e386162b3562
