### ISSUE TITLE
Fehler "Field 'target' doesn't have a default value" nach Neuinstallation

### ISSUE THREAD

**Issue by Steinbam** [terminal42/contao-shortlink#19]
Hi!

Ich habe gerade die aktuelle Version 1.1.1 in meiner Contao Version 4.9.34 neu installiert, hatte die Extension bisher also nicht installiert.

Wenn ich im Backend nun auf "Neuer Kurzlink" klicke, erhalte ich folgenden Fehler:
> Internal Server Error
> An exception occurred while executing 'INSERT INTO tl_terminal42_shortlink (dateAdded, tstamp) VALUES (1663747849, 0)': SQLSTATE[HY000]: General error: 1364 Field 'target' doesn't have a default value

Könnt ihr mal schauen, was hier falsch lief?
Die default configuration habe ich in _app/config/config.yml_ eingefügt und entsprechend angepasst (host eingefügt und salt geändert)

Danke!

**Comment by mrflory** [comment]
Hi, kann das gleiche Problem bestätigen mit Contao 4.13.10.

**Comment by aschempp** [comment]
behoben in 328018618f7a543556a01df20c9ecb7f25f98ece (Version 1.1.2)
