### ISSUE TITLE
Shortlink breaks "Require an item"

### ISSUE THREAD

**Issue by bennyborn** [terminal42/contao-shortlink#20]
As soon as this extension is installed the user won't be able to save a page which has `Require an item` activated.

![image](https://user-images.githubusercontent.com/226890/193818235-faed9bba-9408-4eca-afd2-bd81834c5bc9.png)
![image](https://user-images.githubusercontent.com/226890/193818466-75ab68b3-4cc4-4db5-98fa-a33c30c74263.png)

Tested in Contao 4.13.10

**Comment by aschempp** [comment]
fixed by https://github.com/contao/contao/pull/5366
