### ISSUE TITLE
Unterscheidung Groß-/Kleinschreibung Alias deaktivieren

### ISSUE THREAD

**Issue by thescrat** [terminal42/contao-shortlink#21]
Hi,

beim Aufruf des Alias wird dieser mit Groß-/Kleinschreibung verarbeitet.

Beispiel (Alias "Test")
www.domain.tld/Test -> www.domain.tld/hinterlegte-Weiterleitung/
www.domain.tld/test -> 404 not found
www.domain.tld/TEST -> 404 not found

Im Backend kann ich jedoch keine n-Varianten des Alias anlegen. Eine weitere Variation wird vom System nicht zugelassen weil "bereits vorhanden".

Es wäre daher gut den Alias immer einheitlich zu verarbeiten, egal ob ich Test, test, tESt usw. verwende.

Dankeschön

**Comment by aschempp** [comment]
should be fixed in version 1.2.1

**Comment by thescrat** [comment]
Leider noch nicht gefixt. Gibt man weiterhin ein nicht exakt hinterlegtes /{url_fragment} ein, erhält man einen 404
Möglicherweise sollte der alias in der URL ebenfalls str2lower geprüft werden.
