### ISSUE TITLE
FR: Link prefix option

### ISSUE THREAD

**Issue by hamidpeywasti** [terminal42/contao-shortlink#22]
Hi,

It's good to have an option like "**link prefix**" so that the generated links are distinguished from the original links of the website. For example `https://test.com/go/short-url`.

Currently, if you have an page with alias "about" and create a short link with the `about` Alias. That page will be ignored and link redirected to target of short link! (Bug!?)

With this option, **shortlink** routing will only trigger if the prefix is present. Otherwise the main Cantao structure routing will work. There was no conflict. And when there is a lot of short links, the response will be faster (I think!).

I know that it's possible to use subdomain or other domain for have this feature.

Thanks

**Comment by aschempp** [comment]
The feature has been added in version 1.4 😎
