### ISSUE TITLE
No alias is generated in Contao 4.13

### ISSUE THREAD

**Issue by Steinbam** [terminal42/contao-shortlink#26]
Hi!

The new version 1.3.2 still doesn't seem to work properly with Contao 4.13.38:
If the alias is left empty when creating a new shortlink, no alias is generated when the new shortlink is saved. See line # 1 in the screenshot.

Additionally, I remember that in version 1.2.x the alias was displayed as a clickable link in the table of shortlinks. Now this is also gone, even when I add an alias manually for a new shortlink (line # 2).

I am still using the same configuration properties in config/config.yml ...

![Screenshot](https://github.com/terminal42/contao-shortlink/assets/114060390/e4afbcb0-d1ef-4d38-bde5-55912ad3a231)

**Comment by aschempp** [comment]
Thanks for the report, should be fixed in version 1.3.3
