### ISSUE TITLE
Suggestion: Duplicating shorlink with resetting the number of Visitors

### ISSUE THREAD

**Issue by hamidpeywasti** [terminal42/contao-shortlink#28]
Hi,
By duplicating shortlinks, the number of Visitors (logs) is also is duplicated. Usually this is not expected. It is better not to exclude `logs` from the copy or maybe have a **reset option** for the number of Visitors.

**Comment by aschempp** [comment]
Should be fixed by 07a3b67a751b56265b5fc01b9a3dcc81e851594e
