### ISSUE TITLE
Frontend element that displays current shortlink

### ISSUE THREAD

**Issue by felixww** [terminal42/contao-shortlink#29]
Suggestion:
I dearly miss a frontend content element – or an insert tag, for what it's worth – that displays the shortlink pointing to the current page, if there is one. 
I would use this to add "recommend" or "share this" buttons near blog articles. 
For example, I would add a (fictitious) contao content element "Shortlinks > Link to current page" above every newsreader module. This would produce the URL "shrt.lnk/mnbtsdg" above the news article "Man Bites His Own Dog! Read This Or Be Doomed!", where such a shortlink was configured, and an empty element where there was none. Using a corresponding content template, I could use this structure to wrap a sharing button around the URL, or to just plainly show the link as text.

**Comment by aschempp** [comment]
I don't think this makes sense in the general perspective of this extension. I also wouldn't work if there are multiple links pointing to the same page. Sorry that's a feature I'm reluctant to add. I would suggest to implement this in your local application, since it is very specific to me.
