### ISSUE TITLE
1.5.2 - Maybe incompatible under Contao 5.3.x LTS

### ISSUE THREAD

**Issue by xx81** [terminal42/contao-shortlink#31]
I tried to use the Version 1.5.2 under Contao CMS 5.3.x (LTS).

When i try to edit or create a User Group, then the backend crashes:

``
ErrorException:
Warning: Undefined array key "fields"

  at vendor/contao/core-bundle/contao/dca/tl_user_group.php:390
  at tl_user_group->getExcludedFields()
     (vendor/contao/core-bundle/contao/library/Contao/Widget.php:1311)
  at Contao\Widget::getAttributesFromDca()
     (vendor/contao/core-bundle/contao/classes/DataContainer.php:481)
  at Contao\DataContainer->row()
     (vendor/contao/core-bundle/contao/drivers/DC_Table.php:2175)
  at Contao\DC_Table->edit()
     (vendor/contao/core-bundle/contao/classes/Backend.php:546)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/contao/controllers/BackendMain.php:144)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:44)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:181)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:42)         
``

Here are the composer.json-Packages i use:

![grafik](https://github.com/user-attachments/assets/64687708-34a4-4fce-a6da-6db8e9d85d47)

When i remove the contao-shortlink-Extension I can normaly create/edit a user group.

**Comment by xx81** [comment]
@fritzmg 

Hey Fritz, kannst Du mir einen kurzen Hint geben, warum das aus Contao-Core kommt ? Weil dann müsste ja das Problem auch auftreten, wenn keine externe Erweiterung auftritt?

ich habe das Stack auch mit ungefähr 15 weiteren Erweiterungen gefahren und es tritt immer nur bei dem Short-Link auf, wenn dieses installiert ist.

**Comment by fritzmg** [comment]
> Hey Fritz, kannst Du mir einen kurzen Hint geben, warum das aus Contao-Core kommt ?

The problem originates here: https://github.com/contao/contao/blob/8bc40f32061b3c5ba437b55f7e8803df951f975c/core-bundle/contao/dca/tl_user_group.php#L390

> Weil dann müsste ja das Problem auch auftreten, wenn keine externe Erweiterung auftritt?

No, only with extensions that define a DCA without the `fields` key (wich is otherwise supported in Contao).
