### ISSUE TITLE
"Enable short link" flag gets ignored

### ISSUE THREAD

**Issue by richardhj** [terminal42/contao-shortlink#5]
"Enable short link" flag gets ignored.
The short link will be followed nonetheless.

**Comment by richardhj** [comment]
https://github.com/terminal42/contao-shortlink/blob/ce8c4c9b224cb8dbd689f22f9f329b3b3b3867b9/src/Repository/ShortlinkRepository.php#L44-L52
The condition surely needs to be inverted.

**Comment by aschempp** [comment]
Unfortunately, "frontend preview" does probably not work in that case. Because routing is not done yet, we do not have a firewall, so we don't have a token 😉
