### ISSUE TITLE
post-install-cmd event terminated with an exception

### ISSUE THREAD

**Issue by bogensee** [terminal42/contao-shortlink#7]
During the upgrade to contao 4.9.10 follow error appears. 
The update was cancelled.

`> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception In ScriptHandler.php line 89:
                                                                               
  An error occurred while executing the "contao:install-web-dir" command:      
  In ShortlinkRepository.php line 22:                                          

    Argument 1 passed to Terminal42\ShortlinkBundle\Repository\ShortlinkRepository::__construct() must be an instance of Symfony\Bridge\Doctrine\RegistryInterface, instance of Doctrine\Bundle\DoctrineBundle\Registry given, called in ***/var/cache/prod/ContainerMYAUpkQ/appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php on line 2260`

**Comment by aschempp** [comment]
@richardhj any idea? Might be related to doctrine bundle v3, maybe we should require v2 for now?
/cc @leofeyer

**Comment by richardhj** [comment]
I guess it is as easy as using the new interface. See #8.

**Comment by richardhj** [comment]
I was able to run this extension in Contao 4.7 and 4.9 now

**Comment by aschempp** [comment]
Closed in favor of https://github.com/terminal42/contao-shortlink/pull/8
