### ISSUE TITLE
Shortlinks with a slash in its name to selected Contao pages do not work

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-shortlink#9]
**Reproduction**

1. Create a new short link.
2. Use the picker to select a Contao page for the target. This will insert `{{link_url::5}}`  for example.
3. Use an alias with a `/`, e.g.: `lorem/ipsum`.
4. Open the short link in the front end.

`https://example.com/lorem/ipsum` will redirect to `https://example.com/lorem/target` instead of `https://example.com/target`.

**Cause**

The reason for this is that the `{{link_url::*}}` insert tag generates relative links without a leading slash by default (because it relies on the `base href` of the Contao front end). Sending a `Location: target` response header will cause a redirect relative to the current document's path.

Not sure what the best way to solve this is though. Sure, one can simply use `{{link_url::5|absolute}}` for the target instead, but that's not what the page picker automatically inserts and thus is not very friendly for the editors who work with the extension.

**Comment by aschempp** [comment]
Does this problem happen as well if you use a separate domain for short links?

**Comment by fritzmg** [comment]
In that case it would probably not be a problem, yeah, since Contao would automatically generate absolute URLs then. But that's not how at least our customers want to use this extension :)

**Comment by fritzmg** [comment]
Related to https://github.com/contao/contao/issues/3065

**Comment by fritzmg** [comment]
@aschempp the fix only works for `{{link` insert tags, but presumably any other insert tags (e.g. `{{news_url` etc.) will still not work.

**Comment by aschempp** [comment]
that's true, unfortunately I don't think this will be easy to solve (read: should be solved in Contao)

**Comment by fritzmg** [comment]
I agree.
